# Generated by Django 3.1.4 on 2020-12-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodapp.category')),
            ],
        ),
    ]
